
samples:
    m001: results_annotation/searches/myo.Myosin.domains.fasta.split/myo.Myosin.domains.part_001.fasta
    m002: results_annotation/searches/myo.Myosin.domains.fasta.split/myo.Myosin.domains.part_002.fasta
    m003: results_annotation/searches/myo.Myosin.domains.fasta.split/myo.Myosin.domains.part_003.fasta

# pipeline - a series of rules which be run as a continuous pipeline

align:
  mafft_params: "--maxiterate 100 --genafpair"

trim:
  clipkit_params: "-m kpic-gappy -g 0.7"

#phylogeny:
 # fasta: "results/sample.tree.aln"  
  #outprefix: "results/sample.tree"

#
#generax:
#  tree: "results/sample.tree"
#  fasta: "results/sample.tree.aln"
#  outdir: "results/"
#
#possvm:
#  treefile: "results/sample.tree"
#  refnames: "reference_names.txt"
#

# SEARCH
hmm_dir: data/hmms/
