# GENERAL NOTES
  # Passing parameters to tools:
    # For options ending with <_params> you can put any commandline options for the tool here, as they are normally used, except those that are defined separately in this config file. If you do not wish to specify any parameters, then simply leave the option with "". If an option is defined separately here, then it is simply to require the user to specify input for that parameter.

# WORKFLOW CONTROL
  # Rules indicated here will be run if TRUE (in double quotes), skipped if set to anything else

ww_cl: # workflow_control
  # INITIAL ORTHOLOGY
    # You must enable at least ONE
  broccoli: "TRUE"
  orthofinder: "TRUE"

  ## SEARCH
    # You must enable at least ONE
  search: "TRUE" # runs hmmsearch against gene families and hmm profiles specified by YOU in WORKFLOW PARAMETERS
  downstream_all: "TRUE" # if TRUE then ALL orthogroups identified by INITIAL ORTHOLOGY will be subject to downstream analyses

  ## CLUSTER
  diamond_mcl: "TRUE"

# WORKFLOW PARAMETERS

  # WHOLE WORKFLOW
    # Toy data:
#input_dir: "Broccoli/example_dataset" # path to directory (relative or absolute) containing protein fastas
#output_dir: "results/toy" # path to directory in which all results will be stored

    # Test data:
input_dir: "data/input"
output_dir: "results/test" # path to directory in which all results will be stored

  # INITAL ORTHOLOGY

broccoli:
  broccoli_params: "-kmer_size 10000 -phylogenies ml"

orthofinder:
  orthofinder_params: ""

  # SEARCH

search:
  # Toy data:
  #gene_family_info: data/genefam.tsv
  #gene_family_name: Myosin
  #hmm_dir: data/hmms

  # Test data:
  gene_family_info: /users/asebe/gzolotarov/projects/2021_TFevol/metazoan_tf_evol_2022/results_phylogenies/gene_families_searchinfo.csv
  gene_family_name: Myosin
  hmm_dir: /users/asebe/gzolotarov/projects/2021_TFevol/metazoan_tf_evol_2022/results_phylogenies/hmms

  # CLUSTER

cluster_diamond_mcl:
  diamond_params: "--max-target-seqs 100 --more-sensitive --quiet"

  mcl_params: "--abc"
  mcl_inflation: "1.5"
