search:
  gene_family_info: data/genefam.tsv
  gene_family_name: Myosin
  hmm_dir: data/hmms

samples:
  OG0000000: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000000.fa"
  OG0000001: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000001.fa"
  OG0000002: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000002.fa"
  OG0000003: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000003.fa"
  OG0000004: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000004.fa"
  OG0000005: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000005.fa"
  OG0000006: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000006.fa"
  OG0000007: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000007.fa"
  OG0000008: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000008.fa"
  OG0000009: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000009.fa"
  OG0000010: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000010.fa"
  OG0000011: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000011.fa"
  OG0000012: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000012.fa"
  OG0000013: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000013.fa"
  OG0000014: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000014.fa"
  OG0000015: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000015.fa"
  OG0000016: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000016.fa"
  OG0000017: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000017.fa"
  OG0000018: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000018.fa"
  OG0000019: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000019.fa"
  OG0000020: "results_annotation/OrthoFinder/Results_Oct18/Orthogroup_Sequences/OG0000020.fa"

