executor: slurm
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-%j-{rule}
    --output=logs/{rule}/smk-%j-{rule}.out
    --error=logs/{rule}/smk-%j-{rule}.err
    --time={resources.time}
default-resources: # anything that is not an integer must be double & single quoted e.g. "'64partition'" "'important-thing_69'"
        account: "'dmckeown'"
        paritition: "'genoa64'"
        qos: "'normal'"
        time: "'00-02:00:00'"
        mem_mb: 16000
        threads: 8
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
jobs: 800
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

# SET SPECIFIC RESOURCES FOR SPECIFIC RULES
set-resources:
    search_orthofinder:
        qos: "'vshort'"
        time: "'00-01:00:00'"
        mem_mb: 8000
        threads: 4
    search_broccoli:
        qos: "'vshort'"
        time: "'00-01:00:00'"
        mem_mb: 8000
        threads: 4

