executor: slurm
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-%j-{rule}
    --output=logs/{rule}/smk-%j-{rule}.out
    --error=logs/{rule}/smk-%j-{rule}.err
    --time={resources.time}
default-resources:
  - partition=genoa64
  - qos=vshort
  - threads=6
  - mem_mb=16000
  - time="00-01:00:00"
  - account=dmckeown
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
jobs: 4
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True